#!/bin/bash

sudo apt-get update && sudo apt-get upgrade -y

# Install base libraries
sudo apt-get install -y build-essential libevent-dev libncurses5-dev apt-transport-https \
libncursesw5-dev autotools-dev automake pkg-config vim emacs openssh-server net-tools autoconf \
libtool valgrind python-pip python3-pip flex texinfo lzip bison libtool-bin

##Install Sublime Text 3
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install sublime-text

## getup .gdbinit
cd ~
wget -P ~ git.io/.gdbinit

## Install VScode
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt-get update
sudo apt-get install code
rm -f packages.microsoft.gpg


sudo apt-get dist-upgrade -y

