#!/bin/bash

pushd ~

## Perform a full update and upgrade 
sudo apt update && sudo apt upgrade -y

## Install base libraries
sudo apt-get install -y build-essential libevent-dev libcunit1 libcunit1-dev libncurses5-dev apt-transport-https \
libncursesw5-dev autotools-dev automake pkg-config vim emacs openssh-server net-tools autoconf \
libtool valgrind python3-pip vim make flex texinfo lzip bison libtool-bin bc cvs open-vm-tools \
open-vm-tools-desktop snapd curl

## Install Sublime Text 3
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update
sudo apt install sublime-text

## Get .gdbinit
pushd ~ # Just in case we are moved
wget -P ~ git.io/.gdbinit
popd

## Install VS Code
sudo snap install --classic code # or code-insiders
sudo apt update


## Lastly, perform a dist-upgrade (if there is one) 
sudo apt dist-upgrade -y

popd
