#!/usr/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
UBUNTU_ROOT=$SCRIPT_DIR/..

# Copy update script
sudo cp $UBUNTU_ROOT/day2day/update /usr/bin/

# Copy git aliases to git config
cp $UBUNTU_ROOT/git/.gitconfig

# Copy over .bashrc
cp $UBUNTU_ROOT/terminal/.bashrc

# Move to home directory
pushd ~

# Source .bashrc
source .bashrc

## Perform a full update and upgrade 
sudo apt update && sudo apt upgrade -y

## Install base libraries
sudo apt-get install -y build-essential libevent-dev libcunit1 libcunit1-dev apt-transport-https \
autotools-dev automake pkg-config vim emacs openssh-server net-tools autoconf libtool \
valgrind python3-pip vim make flex texinfo lzip bison libtool-bin bc cvs curl manpages-posix \
manpages-posix-dev glibc-doc glibc-doc-reference software-properties-common wget i3 i3blocks i3status

## Install i3-gaps
# Check if this is Ubuntu 22, as of 4/23/22
# there isn't an apt repo set up yet, need to bail
# otherwise will dork up the sources.list
if grep -q 22.04 /etc/lsb-release; then
    echo "Distribution is Ubuntu 22.04.XX, cannot install i3-gaps via apt..."
else
    echo "***** INSTALLING i3-gaps *****"
    sudo add-apt-repository -y ppa:regolith-linux/stable && \
    sudo apt install i3-gaps
fi

## Install Sublime Text 3
echo "***** INSTALLING Sublime Text 3 *****"
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - && \
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list && \
sudo apt update && sudo apt install sublime-text

## Get .gdbinit
echo "***** INSTALLING GDBinit FILE *****"
pushd ~ # Just in case we are moved
wget -P ~ git.io/.gdbinit
popd

## Install VS Code
echo "***** INSTALLING Vscode *****"
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/ms-vscode-keyring.gpg && \
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ms-vscode-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" | sudo tee /etc/apt/sources.list.d/vscode.list && \
sudo apt update && sudo apt install -y code

## Lastly, perform a dist-upgrade (if there is one) and clean
sudo apt dist-upgrade -y && sudo apt autoremove -y

popd
