#!/bin/bash

#
#wget http://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-7.3.0/gcc-7.3.0.tar.gz


BASE="ftp.gnu.org/gnu/gcc/"
GETNEWEST=0
CURRENT=$(gcc --version | head -n1 | awk '{print $3}') ; echo $CURRENT

NEWEST=$(curl -l ftp.gnu.org/gnu/gcc/ 2>/dev/null | 
        tail -q -n10 | 
        grep -i gcc-[0-9] | 
        awk -F '-' '{print $2}' | 
        sort -r | 
        head -n1) ; echo $NEWEST
if [ ${NEWEST:0:1} -gt ${CURRENT:0:1} ]; then

    echo "$NEWEST is the biggest"
    GETNEWEST=$((GETNEWEST+1))

elif [ ${NEWEST:0:1} -eq ${CURRENT:0:1} ]; then
    echo "Major numbers are the same"

    if [ ${NEWEST:2:1} -gt ${CURRENT:2:1} ]; then
        echo "$NEWEST is the biggest"
        GETNEWEST=$((GETNEWEST+1))

    elif [ ${NEWEST:2:1} -eq ${CURRENT:2:1} ]; then
        echo "Minor numbers are the same"

        if [ ${NEWEST:4:1} -gt ${CURRENT:4:1} ]; then
            echo "$NEWEST is the biggest"
            GETNEWEST=$((GETNEWEST+1))

        elif [ ${NEWEST:4:1} -eq ${CURRENT:4:1} ]; then
            echo "Patch numbers are the same"

        else
            echo "dafuq"
        fi

    else
        echo "dafuq"
    fi

else
    echo "dafuq"
fi

if [ $GETNEWEST != 0 ]; then
    echo "$GETNEWEST Getting newest gcc source"
    wget https://$BASE"gcc-"$NEWEST"/gcc-"$NEWEST".tar.gz"
    tar xvf "gcc-"$NEWEST".tar.gz"
    cd "gcc-"$NEWEST
    pwd
    sudo yum -y install bzip2
    ./contrib/download_prerequisites
    ./configure --disable-multilib --enable-languages=c,c++  
    make -j 4
    sudo make install
    cd -
    rm -rf "gcc-"$NEWEST "gcc-"$NEWEST".tar.gz"
    
else
    echo "Your version of gcc is up-to-date!"
fi




